### ISSUE TITLE
Compatibilidade da biblioteca com distribuições Linux

### ISSUE THREAD

**Issue by TimoteoAlves** [Thiago-cz/all-books#13]
### Question

Compatibilidade da biblioteca com distribuições Linux

### Context

Gostaria de saber se a biblioteca foi testada e é totalmente compatível com diferentes distribuições Linux. Há alguma distribuição específica que vocês recomendam ou sabem que apresenta problemas conhecidos? Seria útil adicionar à documentação uma seção sobre como instalar e configurar a biblioteca em sistemas Linux, incluindo possíveis dependências e dicas de solução de problemas

**Comment by TimoteoAlves** [comment]
...

**Comment by Thiago-cz** [comment]
A nossa biblioteca foi testada e é totalmente compatível com a distribuição Ubuntu 20.04. No momento, garantimos suporte apenas para essa versão específica do Ubuntu.

Infelizmente, não podemos assegurar o funcionamento em outras distribuições Linux, pois elas não foram testadas e podem apresentar problemas de compatibilidade.

É uma ótima sugestão incluir na documentação uma seção sobre a instalação e configuração da biblioteca em sistemas Linux, com detalhes sobre dependências e dicas de solução de problemas. Vamos considerar essa adição em futuras atualizações.

Se você estiver utilizando Ubuntu 20.04 e encontrar algum problema, por favor, nos avise!
